#
# use:    JoseQuintas/harbour_34/hb34_0703
# create: deleted_hb
#

name: deleted_hb

on:
  push:
  schedule:
   - cron: "30 2 1 * *"
  workflow_dispatch:
    inputs:
      name:
        description: 'deleted_hb'
        default: 'deleted_hb'
        required: true

jobs:

  Build:
    runs-on: windows-latest
    steps:

    - name: install harbour
      uses: JoseQuintas/action-download-artifact@v2
      with:
         workflow: hb34_0703.yml
         workflow_conclusion: success
         name: hb34_0703
         path: c:\temp
         repo: JoseQuintas/harbour_34

    - name: install mingw
      uses: JoseQuintas/action-download-artifact@v2
      with:
         workflow: hb34_0703.yml
         workflow_conclusion: success
         name: mingw_0703
         path: c:\temp
         repo: JoseQuintas/harbour_34

    - name: Unzip
      run: |
         c:
         dir c:\temp
         md c:\temp\harbour
         7z x -y c:\temp\hb34_0703.7z -oc:\temp\harbour
         7z x -y c:\temp\mingw_0703.7z -oc:\temp\mingw

    - name: Install Source Code
      env:
         REPO: ${{ github.repository }}
      run: |
         c:
         md \temp\harbour\addons
         git clone https://github.com/$env:repo c:\temp\deleted_hb --depth 10

    - name: Build 32 bits
      env:
         HB_COMPILER: mingw
         HB_INSTALL_PREFIX: c:\temp\harbour
         PATH: c:\temp\harbour\bin;c:\temp\mingw\mingw64\bin
      run: |
         c:
         cd \temp\deleted_hb
         hbmk2 *.hbp

    - name: Build 64 bits
      env:
         HB_COMPILER: mingw64
         HB_INSTALL_PREFIX: c:\temp\harbour
         PATH: c:\temp\harbour\bin;c:\temp\mingw\mingw64\bin
      run: |
         c:
         cd \temp\deleted_hb
         hbmk2 *.hbp

    - name: Zip
      env:
         PATH: c:\program files\7-zip
      run: |
         c:
         cd \temp\deleted_hb
         7z a -r c:\temp\deleted_hb.7z c:\temp\deleted_hb\*.*  -xr'!.git' -xr'!.github' -xr'!.hbmk'

    - name: Save
      uses: actions/upload-artifact@v2
      with:
         name: deleted_hb
         path: c:\temp\deleted_hb.7z
